#	R --no-restore --no-save --slave < ./API_R_Plots_IBES.cmd
BB68_data <- read.table("./Country_Results/AUS/APIs_IBES_to_plot_AUS.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/AUS/F3_API_plot_base_case_AUS.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("AUS--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/CAN/APIs_IBES_to_plot_CAN.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/CAN/F3_API_plot_base_case_CAN.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("CAN--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/CHN/APIs_IBES_to_plot_CHN.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/CHN/F3_API_plot_base_case_CHN.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("CHN--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/DEU/APIs_IBES_to_plot_DEU.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/DEU/F3_API_plot_base_case_DEU.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("DEU--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/FRA/APIs_IBES_to_plot_FRA.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/FRA/F3_API_plot_base_case_FRA.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("FRA--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/GBR/APIs_IBES_to_plot_GBR.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/GBR/F3_API_plot_base_case_GBR.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("GBR--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/HKG/APIs_IBES_to_plot_HKG.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/HKG/F3_API_plot_base_case_HKG.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("HKG--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/IDN/APIs_IBES_to_plot_IDN.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/IDN/F3_API_plot_base_case_IDN.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("IDN--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/JPN/APIs_IBES_to_plot_JPN.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/JPN/F3_API_plot_base_case_JPN.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("JPN--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/KOR/APIs_IBES_to_plot_KOR.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/KOR/F3_API_plot_base_case_KOR.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("KOR--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/MYS/APIs_IBES_to_plot_MYS.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/MYS/F3_API_plot_base_case_MYS.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("MYS--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/NZL/APIs_IBES_to_plot_NZL.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/NZL/F3_API_plot_base_case_NZL.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("NZL--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/PHL/APIs_IBES_to_plot_PHL.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/PHL/F3_API_plot_base_case_PHL.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("PHL--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/SGP/APIs_IBES_to_plot_SGP.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/SGP/F3_API_plot_base_case_SGP.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("SGP--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/THA/APIs_IBES_to_plot_THA.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/THA/F3_API_plot_base_case_THA.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("THA--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
BB68_data <- read.table("./Country_Results/TWN/APIs_IBES_to_plot_TWN.txt",sep="	",stringsAsFactors=FALSE,header=TRUE)
x <- as.numeric(BB68_data[1:540, "Day"])
xrange <- range(-400,200)
y1 <- BB68_data[1:540, "API_Good_News"]
y2 <- BB68_data[1:540, "API_Bad_News"]
y2 <- (y2 - y2[1])
y3 <- (y1 + y2)/2
y1 <- (y1 - y3)
y2 <- (y2 - y3)
y1range <- range(y1)
y2range <- range(y2)
api_min = min(c(range(y1),range(y2)))
api_min <- floor(100*api_min)/100
api_max = max(c(range(y1),range(y2)))
api_max <- ceiling(100*api_max)/100
yrange <- range(api_min,api_max)
colors <- rainbow(2)
pdf("./Country_Results/TWN/F3_API_plot_base_case_TWN.pdf")
plot(xrange, yrange, type="n", xlab="Event Day", ylab="API")
lines(x,y1,type="l", lwd=1.5, col="green")
lines(x,y2,type="l", lwd=1.5, col="red")
abline(v=0, lty=3, lwd=1, col="black")
abline(h=0, lty=1, lwd=1, col="black")
legend(bty="n", xrange[1], yrange[2], c("Good News","Bad News"), col=c("green","red"), lty=1:1)
title(cex.main=1, main = paste("TWN--IBES, base case"))
dev.off( )
rm(y1,y2,y3)
q( )
