echo "$(date) Starting to generate API plot input data for AUS"
sort -k1,6 -k7g ./Country_Results/AUS/APIs_IBES_std_output_AUS.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/AUS/APIs_IBES_to_plot_AUS.txt
echo "$(date) Starting to generate API plot input data for CAN"
sort -k1,6 -k7g ./Country_Results/CAN/APIs_IBES_std_output_CAN.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/CAN/APIs_IBES_to_plot_CAN.txt
echo "$(date) Starting to generate API plot input data for CHN"
sort -k1,6 -k7g ./Country_Results/CHN/APIs_IBES_std_output_CHN.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/CHN/APIs_IBES_to_plot_CHN.txt
echo "$(date) Starting to generate API plot input data for DEU"
sort -k1,6 -k7g ./Country_Results/DEU/APIs_IBES_std_output_DEU.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/DEU/APIs_IBES_to_plot_DEU.txt
echo "$(date) Starting to generate API plot input data for FRA"
sort -k1,6 -k7g ./Country_Results/FRA/APIs_IBES_std_output_FRA.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/FRA/APIs_IBES_to_plot_FRA.txt
echo "$(date) Starting to generate API plot input data for GBR"
sort -k1,6 -k7g ./Country_Results/GBR/APIs_IBES_std_output_GBR.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/GBR/APIs_IBES_to_plot_GBR.txt
echo "$(date) Starting to generate API plot input data for HKG"
sort -k1,6 -k7g ./Country_Results/HKG/APIs_IBES_std_output_HKG.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/HKG/APIs_IBES_to_plot_HKG.txt
echo "$(date) Starting to generate API plot input data for IDN"
sort -k1,6 -k7g ./Country_Results/IDN/APIs_IBES_std_output_IDN.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/IDN/APIs_IBES_to_plot_IDN.txt
echo "$(date) Starting to generate API plot input data for JPN"
sort -k1,6 -k7g ./Country_Results/JPN/APIs_IBES_std_output_JPN.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/JPN/APIs_IBES_to_plot_JPN.txt
echo "$(date) Starting to generate API plot input data for KOR"
sort -k1,6 -k7g ./Country_Results/KOR/APIs_IBES_std_output_KOR.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/KOR/APIs_IBES_to_plot_KOR.txt
echo "$(date) Starting to generate API plot input data for MYS"
sort -k1,6 -k7g ./Country_Results/MYS/APIs_IBES_std_output_MYS.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/MYS/APIs_IBES_to_plot_MYS.txt
echo "$(date) Starting to generate API plot input data for NZL"
sort -k1,6 -k7g ./Country_Results/NZL/APIs_IBES_std_output_NZL.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/NZL/APIs_IBES_to_plot_NZL.txt
echo "$(date) Starting to generate API plot input data for PHL"
sort -k1,6 -k7g ./Country_Results/PHL/APIs_IBES_std_output_PHL.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/PHL/APIs_IBES_to_plot_PHL.txt
echo "$(date) Starting to generate API plot input data for SGP"
sort -k1,6 -k7g ./Country_Results/SGP/APIs_IBES_std_output_SGP.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/SGP/APIs_IBES_to_plot_SGP.txt
echo "$(date) Starting to generate API plot input data for THA"
sort -k1,6 -k7g ./Country_Results/THA/APIs_IBES_std_output_THA.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/THA/APIs_IBES_to_plot_THA.txt
echo "$(date) Starting to generate API plot input data for TWN"
sort -k1,6 -k7g ./Country_Results/TWN/APIs_IBES_std_output_TWN.txt | gawk 'BEGIN{FS=OFS="	";print "Day	API_Good_News	Count_Good_News	API_Bad_News	Count_Bad_News"};{if(!($2=="eps")||!($3=="pr_fyr_prev")||!($4=="sign")||($5=="NA")||!($6=="adjror")){next};count[$1 "	" $5]=$9;sum_apis_all_fyrs[$5 "	" $7]+=$8};END{count_all_G=count_all_B=0;for(fyr=1989;fyr<=2017;fyr++){count_all_G+=count[fyr "	G"];count_all_B+=count[fyr "	B"]};for(nd=1;nd<=540;nd++){print nd-360,sum_apis_all_fyrs["G	" nd]/count_all_G,count_all_G,sum_apis_all_fyrs["B	" nd]/count_all_B,count_all_B}}' > ./Country_Results/TWN/APIs_IBES_to_plot_TWN.txt
